### ISSUE TITLE
datanodes not working

### ISSUE THREAD

**Issue by QPOZP** [hitsomeshots/datanodes-link-generator#3]
fuckingfast works, datanode doesn't. If the problem is only with me, any way to debug? Thanks

**Comment by rand0m0User** [comment]
![image](https://github.com/user-attachments/assets/a80b9a04-a54c-4cb0-8f2a-63dc70883eac)
i'd assume they both have changed their Protocall, why cant they be as fun as zippyshare lol, guess il manually have to use the OneDrive links if i see anything worth a damn

**Comment by Anatharias** [comment]
What is this download interface you're showing ?
And BTW, the Datanodes and FF are both working, awesome !

**Comment by hitsomeshots** [comment]
i just tested it and its working.
